### ISSUE TITLE
Import initial code

### ISSUE THREAD

**Issue by nicolas-brousse** [pantographe/view_component-form#1]
- [x] Create empty gem

### Files
- [x] FormBuilder
- [x] Form::BaseComponent
- [x] Form::FieldComponent
- [x] Form::LabelComponent
- [x] Form::TextFieldComponent

### TODO
- [ ] Remove methods that are not generic

**Comment by nicolas-brousse** [comment]
@Spone I've pushed the initial commit :)

**Comment by Spone** [comment]
> Remove methods that are not generic

I think this item is done, what do you think @nicolas-brousse?
