### ISSUE TITLE
Upgrading to 0.2.0 makes app unlaunchable, Zeitwerk-related, stupid hack enclosed

### ISSUE THREAD

**Issue by dhnaranjo** [pantographe/view_component-form#113]
Whattup? So. I'm working with Rails 7.0.2.2, Ruby 3.1.1. I updated to ViewComponent-Form 0.2.0 and then I got:

```
dazmin@Desmonds-MacBook-Pro tmp % rake zeitwerk:check
(in /Users/dazmin/RubymineProjects/omm)
rake aborted!
NameError: uninitialized constant ViewComponent::Form

loader.push_dir("#{__dir__}/form", namespace: ViewComponent::Form)
                                                           ^^^^^^
/Users/dazmin/RubymineProjects/omm/config/application.rb:7:in `<top (required)>'
/Users/dazmin/RubymineProjects/omm/Rakefile:4:in `require_relative'
/Users/dazmin/RubymineProjects/omm/Rakefile:4:in `<top (required)>'

Caused by:
LoadError: cannot load such file -- view_component-form
/Users/dazmin/RubymineProjects/omm/config/application.rb:7:in `<top (required)>'
/Users/dazmin/RubymineProjects/omm/Rakefile:4:in `require_relative'
/Users/dazmin/RubymineProjects/omm/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
dazmin@Desmonds-MacBook-Pro tmp % 
```

Which is bad. I flailed around for a while and ended up with this quite stupid hack that works. https://github.com/dhnaranjo/view_component-form/commit/21d9b467bafc24a2b99096bf882566f7588df032. Short version, since the constant ain't initialized I initialized it.

```diff
# /lib/view_component/form.rb
require "view_component"
require "zeitwerk"

+ module ViewComponent
+   module Form
+   end
+ end

loader = Zeitwerk::Loader.for_gem
form = "#{__dir__}/form.rb"
loader.ignore(form)
```

Anyways, I got no idea how to actually resolve it or I'd happily make a PR. This solution of mine seems too dumb to be proper.

**Comment by tmaier** [comment]
I can confirm this issue in my project.

**Comment by Spone** [comment]
Thanks for opening an issue, we will soon publish a new version with a fix.

**Comment by tmaier** [comment]
Hi @Spone,

would it be possible to release a new version with a fix for this, given that the latest release is currently unusable...

**Comment by nicolas-brousse** [comment]
:wave: thank you for your patience. We've just release a new version that should fix the issue.

Let us know if you still have errors.

**Comment by dhnaranjo** [comment]
Oh, looks like my fix was just dumb enough!

**Comment by Spone** [comment]
> Oh, looks like my fix was just dumb enough!

Yes it was the most straightforward way :)
