### ISSUE TITLE
Unable to load builder with default generator output

### ISSUE THREAD

**Issue by coder2000** [pantographe/view_component-form#137]
The default location that the generator places the builder class of `lib/` isn't loaded automatically by the application and needs to be manually included somewhere. There are are few options:

1. Update the documentation to specify that it needs to be included
2. Add an initializer to the generator that requires the builder
3. Change the generator to put the builder in the `app/helpers` folder instead

**Comment by Spone** [comment]
I'd be OK with option 1, option 3 (but maybe with an `app/forms` folder?), or suggesting both 1 and 3 in the docs.
What do you think @nicolas-brousse?
