### ISSUE TITLE
Support for view components 3.0.0

### ISSUE THREAD

**Issue by kwent** [pantographe/view_component-form#146]
Hi,

Following 3.0.0 release https://github.com/ViewComponent/view_component/blob/main/docs/CHANGELOG.md#v300

I see you released https://rubygems.org/gems/view_component-form/versions/0.2.4 but for some reasons runtime dependencies are set to but your gemspec file do specify `view_component` < 4.0

```
RUNTIME DEPENDENCIES (4):
[actionview](https://rubygems.org/gems/actionview) >= 6.0.0, < 7.1
[activesupport](https://rubygems.org/gems/activesupport) >= 6.0.0, < 7.1
[view_component](https://rubygems.org/gems/view_component) >= 2.34.0, < 3.0
[zeitwerk](https://rubygems.org/gems/zeitwerk) ~> 2.5
```

So something wrong might have happened during the release process.

Regards

**Comment by Spone** [comment]
Thanks for reporting this, we'll look into it!

**Comment by Spone** [comment]
#144 bumps the dependency, we just need to release a new version of the gem. It will be done soon!

**Comment by Spone** [comment]
@kwent you can upgrade to [v0.2.5](https://github.com/pantographe/view_component-form/releases/tag/v0.2.5) :)
