### ISSUE TITLE
Support Rails 7.1

### ISSUE THREAD

**Issue by tmaier** [pantographe/view_component-form#152]
It would be great, if the gem could support Rails 7.1 very soon.

The gem currently requires actionview and activesupport < 7.1. https://github.com/pantographe/view_component-form/blob/main/view_component-form.gemspec#L29

An appraisal for Rails 7.1 + VC 3.0 needs to be defined.
https://github.com/pantographe/view_component-form/blob/db5c588e8eb1e9fb6161a96cab97700ba2234e84/Appraisals#L25C1-L29C1

**Comment by Spone** [comment]
See #151 :)

**Comment by tmaier** [comment]
Sorry. I missed to check the PRs.
