### ISSUE TITLE
Docs: Example for wrapping input in div

### ISSUE THREAD

**Issue by stebo** [pantographe/view_component-form#154]
First off, thanks a lot for providing this awesome gem, exactly what I was looking for! 

In the readme it says
> You can use the same approach to inject options, wrap the input in a div etc.

But I am not sure how to accomplish this - would you create a `text_field_component.html.erb` file for this, or take care of that in `text_field_component.rb` -  what's the best practise way? 

Maybe you can help out with a short example for these classical cases where some div should be wrapped around the input or an icon can be optionally but before/after the input.

Thanks a lot!

**Comment by Spone** [comment]
Hi @stebo, I agree we could elaborate a bit more on this.

First, follow the steps described in the README:
- generate your own `FormBuilder` and pick the namespace your components will be loaded from

```rb
# app/helpers/custom_form_builder.rb
class CustomFormBuilder < ViewComponent::Form::Builder
  # Set the namespace you want to use for your own components
  namespace "Custom::Form"
end
```

- use it in your form

```diff
- <%= form_for @user do |f| %>
+ <%= form_for @user, builder: CustomFormBuilder do |f| %>
```

- generate your own components in the namespace you picked

```
bin/rails generate component Custom::Form::TextField --inline --parent ViewComponent::Form::TextFieldComponent
```

Then, here is how you could wrap the input in a div:

```rb
# app/components/custom/form/text_field_component.rb
class Custom::Form::TextFieldComponent < ViewComponent::Form::TextFieldComponent
  def call
    content_tag :div, super, class: "custom-form-wrapper"
  end
end
```

or with [inline templates](https://viewcomponent.org/guide/templates.html#inline):

```rb
# app/components/custom/form/text_field_component.rb
class Custom::Form::TextFieldComponent < ViewComponent::Form::TextFieldComponent
  erb_template <<~ERB
    <div class="custom-form-wrapper">
      <%= self.class.tag_klass.new(object_name, method_name, @view_context, options).render %>
    </div>
  ERB
end
```

If you prefer, you can do this in a [sibling template file](https://viewcomponent.org/guide/templates.html#sibling-file):

```rb
# app/components/custom/form/text_field_component.rb
class Custom::Form::TextFieldComponent < ViewComponent::Form::TextFieldComponent
  def call
    content_tag :div, super, class: "custom-form-wrapper"
  end
end
```

```erb
# app/components/custom/form/text_field_component.html.erb
<div class="custom-form-wrapper">
  <%= self.class.tag_klass.new(object_name, method_name, @view_context, options).render %>
</div>

```

Let me know if it's clearer :)

--------------

While preparing these examples, I noticed that you cannot use `render_parent` as [described in ViewComponent docs](https://viewcomponent.org/guide/templates.html#rendering-parent-templates). I'm still unsure why, it would need a bit more investigation.

In the meantime, ViewComponent::Form could provide a `render_field` method that would wrap `self.class.tag_klass.new(object_name, method_name, @view_context, options).render` for your convenience.

**Comment by Spone** [comment]
About my last point, actually inheriting directly from the `FieldComponent`(that contains the `call` method), and calling `render_parent_to_string` works:

```rb
class Custom::Form::TextFieldComponent < ViewComponent::Form::FieldComponent
  self.tag_klass = ActionView::Helpers::Tags::TextField

  erb_template <<~ERB
    <div class="custom-form-wrapper">
      <%= render_parent_to_string %>
    </div>
  ERB
end
```

**Comment by stebo** [comment]
Thanks a lot for the information, overwriting the `call` function was what I was missing - but I went with a sibling template file now which gives a bit more freedom for complex templates :)

Thanks also for noting `render_parent_to_string` which works very well!
