### ISSUE TITLE
It'd be nice to have the ability to customize the base class so that it can inherit our own class

### ISSUE THREAD

**Issue by joelzwarrington** [pantographe/view_component-form#159]
It'd be nice if [ViewComponent::Form::BaseComponent](https://github.com/pantographe/view_component-form/blob/280c902e626f31f69ab3164c06d1ddee2504c8c8/app/components/view_component/form/base_component.rb#L5) could be configured so that we can define our own parent class, instead of inheriting from `ViewComponent::Base`.

**Comment by joelzwarrington** [comment]
Is this something you'd be open to if I worked on it?

I was thinking something similar to Devise' `parent_controller` configuration where it'd be defined as a string in configuration via initializer and then used like [this](https://github.com/heartcombo/devise/blob/bb18f4d3805be0bf5f45e21be39625c7cfd9c1d6/app/controllers/devise_controller.rb#L4).

**Comment by Spone** [comment]
Hi @joelzwarrington thanks for opening an issue for this. We discussed related topics in #69 and #80. We're totally open to a PR for this!
