### ISSUE TITLE
Cut release with Rails 7.2 Support

### ISSUE THREAD

**Issue by henrikbjorn** [pantographe/view_component-form#170]
Seems that Rails 7.2 support was merged recently.

Is it possible to get a new version cut with that change?

**Comment by joelzwarrington** [comment]
@nicolas-brousse @Spone would either of you be able to cut a new version? 😄

**Comment by nicolas-brousse** [comment]
@henrikbjorn @joelzwarrington I'll try to publish a new version tomorrow

**Comment by nicolas-brousse** [comment]
v0.2.8 has been released 🙂
