### ISSUE TITLE
Create a custom RSpec matcher for component content

### ISSUE THREAD

**Issue by nicolas-brousse** [pantographe/view_component-form#27]
In our current project, I use to have this kind of tests.

```rb
      expect(component.to_html.tr("\n", "")).to eq <<~HTML.tr("\n", "").strip
        <label class="form-checkbox" for="user_is_enabled">
        <input name="user[is_enabled]" type="hidden" value="0">
        <input class="form-checkbox__input" type="checkbox" value="1" name="user[is_enabled]" id="user_is_enabled">
        <span class="form-checkbox__label">Actif</span>
        </label>
      HTML
```

It's not the cleanest. Maybe we may create a custom matcher like
```rb
      expect(component).to have_html <<~HTML
        <label class="form-checkbox" for="user_is_enabled">
        <input name="user[is_enabled]" type="hidden" value="0">
        <input class="form-checkbox__input" type="checkbox" value="1" name="user[is_enabled]" id="user_is_enabled">
        <span class="form-checkbox__label">Actif</span>
        </label>
      HTML
```

_Originally posted by @nicolas-brousse in https://github.com/pantographe/view_component-form/pull/14#discussion_r661302066_

**Comment by peteryates** [comment]
Would recommend [rspec-html-matchers](https://github.com/kucaahbe/rspec-html-matchers) instead of comparing HTML strings directly.

**Comment by Spone** [comment]
Thanks @peteryates for chiming in!

I think we'll keep comparing HTML strings directly when the output is very simple (a label or a text field), as it makes the spec very readable.

But we'll probably add `rspec-html-matchers` down to road to use on more complex components!
